### ISSUE TITLE
Setting up 1 generated px to 1 real px ratio

### ISSUE THREAD

**Issue by smbdelse** [giventofly/pixelit#13]
Hi!

I'm struggling with setting up pixelit so it would produce image with 1real pixel to 1 generated pixel ratio. Do you think that there is any easy way to do that?

Another way to make any manual post-processing easier would be to have exact dimensions of pixel grid and if it starts from the top-left corner of the image or center. I initially thought that generated pixels would be perfect squares but somehow it was quite hard to fit generated image in a regular grid, especially when it seems that pixels can be a bit cut off close to the edges of image.

EDIT: BTW this library is great, I haven't found anything working better in general :)

EDIT2:
The very quick temporary solution I found was to change this:
https://github.com/giventofly/pixelit/blob/be691097d1f14b21b5c268a9788c80164a702256/dist/pixelit.js#L201-L211

To:
```    
    this.ctx.drawImage(
      tempCanvas,
      0,
      0,
      scaledW,
      scaledH,
      0,
      0,
      scaledW,
      scaledH,
    );
    ```

**Comment by giventofly** [comment]
Hi, 

glad you found a solution before I came here. I thought you were talking about dpi at first and was searching for what could be ( https://stackoverflow.com/questions/54430842/how-can-i-get-dpi-from-image-in-js/54454509#54454509 ) was giving this, since I assumed it would need more changes to fit your needs.

Glad you found a solution.
