### ISSUE TITLE
Pixelated images is not viewing in my game when running in lenovo G560(super old laptop). 

### ISSUE THREAD

**Issue by IgnitedMindss** [giventofly/pixelit#14]
I am using **Pixel it** for creating game assets. When i checked the game.exe in my old laptop, the images used from Pixel it was not showing. It was only showing the images that i have hand drawn. But the images are viewable in latest and mid generations laptops.

**Comment by giventofly** [comment]
That is a bit vague, need to be sure the problem is really arising from the pixel it usage and not from other source.

Since pixel it needs to process every pixel of an image it might be very demanding for older processors and that might cause a crash, nevertheless it should be used like that for a game (in my opinion) you should pre-process the images you want to use and deliver them as a game asset - but I can be wrong, not really sure what is your idea/use.
